parameter_defaults:

    NovaSchedulerDefaultFilters: ['AvailabilityZoneFilter','CoreFilter','RamFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter', 'AggregateInstanceExtraSpecsFilter']
